server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    draiver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  type-aliases-package: com.example.boot.demo.bean
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      example:
        mapper: debug
